{
 "title": "Tacobot",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "guild_id",
    "label": "Guild ID",
    "query": {
     "query": "label_values(tacobot_guilds,guild_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_user_join_leave{guild_id=~\"$guild_id\"}",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_logs{guild_id=~\"$guild_id\", level=~\"WARNING|ERROR\"}",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "🔴 LIVE NOW",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_live_now{guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Team Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_team_requests{instance=\"$collector\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Birthdays",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_birthdays{guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invited Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_invited_users {guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Twitch Linked Accounts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tacobot_twitch_linked_accounts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Giveaway Games Available",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tacobot_game_keys_available {}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Giveaway Games Redeemed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tacobot_game_keys_redeemed {}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Minecraft Whitelisted",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tacobot_minecraft_whitelist", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Twitch Bot Joined Channels",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_twitch_channels{guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gone Live 🔴",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_live_platform {guild_id=~\"$guild_id\"}",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "Twitch Tacos🌮",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_twitch_tacos {guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tacos Earned",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_tacos {guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tacos Gifted",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_taco_gifts {guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🌮 Reactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_taco_reactions {guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Interactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "TQOTD Questions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_tqotd {guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mental Mondays Topics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_mentalmondays{guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taco Tuesday",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_tacotuesday {guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WDYCTW Questions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_wdyctw_questions{guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tech Thursdays Topics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_techthurs{guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "First Messages Today",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tacobot_first_messages_today{guild_id=~\"$guild_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Tracked Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tacobot_messages{guild_id=~\"$guild_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Food Posts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tacobot_food_posts{guild_id=~\"$guild_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TQOTD Answers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_tqotd_answers{guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mental Mondays Interactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_mentalmondays_answers{guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taco Tuesday Interactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_tacotuesday_answers{guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WDYCTW Answers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_wdyctw_answers{guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tech Thursdays Replies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_techthurs_answers{guild_id=~\"$guild_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Known Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tacobot_known_users{guild_id=~\"$guild_id\"}) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Suggestions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacobot_suggestions{guild_id=~\"$guild_id\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Visuals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Trivia By Difficulty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(tacobot_trivia_questions{guild_id=~\"$guild_id\"}) by (difficulty)",
     "legendFormat": "{{difficulty}}"
    }
   ]
  },
  {
   "title": "Trivia By Starter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum(tacobot_trivia_questions{guild_id=~\"$guild_id\"}) by (starter_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Food Post Rate By User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "round(delta(tacobot_food_posts{guild_id=~\"$guild_id\"}[1d]))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Trivia By Category",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum(tacobot_trivia_questions{guild_id=~\"$guild_id\"}) by (category)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Rate By User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "round(delta(tacobot_messages{guild_id=~\"$guild_id\"}[30m]))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Food Post By User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "tacobot_food_posts{guild_id=~\"$guild_id\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Tacos Rate By Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "round(delta(tacobot_taco_logs{guild_id=~\"$guild_id\"}[60m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Messages By User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "tacobot_messages{guild_id=~\"$guild_id\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Gift Rate By User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "round(delta(tacobot_gifters{guild_id=~\"$guild_id\"}[30m]))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Tacos By Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "tacobot_taco_logs{guild_id=~\"$guild_id\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "React Rate By User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "round(delta(tacobot_reactors {guild_id=~\"$guild_id\"}[30m]))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Gift By User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "tacobot_gifters{guild_id=~\"$guild_id\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Tacos Rate By User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "round(delta(tacobot_top_tacos{guild_id=~\"$guild_id\"}[30m]))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Reacts By User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "tacobot_reactors {guild_id=~\"$guild_id\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Taco Receive Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "round(delta(tacobot_tacos{guild_id=~\"$guild_id\"}[30m]))",
     "legendFormat": "Earned"
    },
    {
     "expr": "round(delta(tacobot_taco_gifts{guild_id=~\"$guild_id\"}[60m]))",
     "legendFormat": "Gift"
    },
    {
     "expr": "round(delta(tacobot_taco_reactions{guild_id=~\"$guild_id\"}[60m]))",
     "legendFormat": "Reactions"
    },
    {
     "expr": "round(delta(tacobot_twitch_tacos{guild_id=~\"$guild_id\"}[60m]))",
     "legendFormat": "Twitch"
    }
   ]
  },
  {
   "title": "Tacos Rate By User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "tacobot_top_tacos{guild_id=~\"$guild_id\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Tacos 🌮 Earned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "tacobot_tacos{guild_id=~\"$guild_id\"}",
     "legendFormat": "TACOS 🌮"
    }
   ]
  },
  {
   "title": "TACOs 🌮",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "expr": "tacobot_taco_gifts {guild_id=~\"$guild_id\"}",
     "legendFormat": "Gifts"
    },
    {
     "expr": "tacobot_taco_reactions {guild_id=~\"$guild_id\"}",
     "legendFormat": "Reactions"
    },
    {
     "expr": "tacobot_twitch_tacos {guild_id=~\"$guild_id\"}",
     "legendFormat": "Twitch"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "sum(round(delta(tacobot_messages{guild_id=~\"$guild_id\"}[30m])))",
     "legendFormat": "Messages"
    },
    {
     "expr": "round(delta(tacobot_first_messages_today{guild_id=~\"$guild_id\"}[60m]))",
     "legendFormat": "First Message"
    }
   ]
  },
  {
   "title": "Logs Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 111 },
   "targets": [
    {
     "expr": "round(delta(tacobot_logs{guild_id=~\"$guild_id\"}[60m]))\r\n",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 111 },
   "targets": [
    {
     "expr": "tacobot_logs{guild_id=~\"$guild_id\"}",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "🔴 Going Live ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "round(delta(tacobot_live_twitch{guild_id=~\"$guild_id\"}[60m]))",
     "legendFormat": "Twitch"
    },
    {
     "expr": "round(delta(tacobot_live_youtube{guild_id=~\"$guild_id\"}[60m]))",
     "legendFormat": "Youtube"
    }
   ]
  },
  {
   "title": "🔴 LIVE NOW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "targets": [
    {
     "expr": "tacobot_live_now{guild_id=~\"$guild_id\"}",
     "legendFormat": "Live"
    }
   ]
  },
  {
   "title": "Interaction Topics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "round(delta(tacobot_mentalmondays{guild_id=~\"$guild_id\"}[24h]))",
     "legendFormat": "Mental Monday"
    },
    {
     "expr": "round(delta(tacobot_tacotuesday{guild_id=~\"$guild_id\"}[24h]))",
     "legendFormat": "Taco Tuesday"
    },
    {
     "expr": "round(delta(tacobot_wdyctw_questions{guild_id=~\"$guild_id\"}[24h]))",
     "legendFormat": "WDYCTW"
    },
    {
     "expr": "round(delta(tacobot_techthurs{guild_id=~\"$guild_id\"}[24h]))",
     "legendFormat": "Tech Thursday"
    },
    {
     "expr": "round(delta(tacobot_tqotd{guild_id=~\"$guild_id\"}[24h]))",
     "legendFormat": "TQOTD"
    }
   ]
  },
  {
   "title": "🔴 Live By User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "targets": [
    {
     "expr": "tacobot_live_activity {guild_id=~\"$guild_id\", platform!=\"\"}",
     "legendFormat": "{{username}} ({{platform}})"
    }
   ]
  },
  {
   "title": "Interactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "targets": [
    {
     "expr": "round(delta(tacobot_tqotd_answers{guild_id=~\"$guild_id\"}[24h]))",
     "legendFormat": "TQOTD"
    },
    {
     "expr": "round(delta(tacobot_mentalmondays_answers{guild_id=~\"$guild_id\"}[24h]))",
     "legendFormat": "Mental Monday"
    },
    {
     "expr": "round(delta(tacobot_tacotuesday_answers{guild_id=~\"$guild_id\"}[24h]))",
     "legendFormat": "Taco Tuesday"
    },
    {
     "expr": "round(delta(tacobot_wdyctw_answers{guild_id=~\"$guild_id\"}[24h]))",
     "legendFormat": "WDYCTW"
    },
    {
     "expr": "round(delta(tacobot_techthurs_answers{guild_id=~\"$guild_id\"}[24h]))",
     "legendFormat": "Tech Thursday"
    }
   ]
  }
 ]
}